# ============ 公共配置 ============
spring:
  jackson:  # Jackson序列化配置
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:  # Freemarker配置
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl  # 后缀.ftl可省略
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common  # 将common.ftl设置为包文件并设置别名为common

mybatis-plus:  # MyBatis配置
  type-aliases-package: com.gedoumi.quwabao  # 别名包
  mapper-locations: classpath:mappers/**/**.xml  # xml文件位置
  #  type-enums-package:
  global-config:  # MyBatis-Plus配置
    db-config:  # 数据库相关配置
      id-type: id_worker  # 主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      field-strategy: not_empty  # 字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #capital-mode: true  # 数据库大写下划线转换
      db-type: mysql  # 数据库类型
    refresh: true  # 刷新mapper 调试神器
  configuration:  # 原生Mybatis配置
    cache-enabled: false  # 关闭缓存
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则
    use-generated-keys: true  # 自动生成主键
    default-executor-type: reuse  # 配置默认的执行器（REUSE 执行器会重用预处理语句）
    default-statement-timeout: 600  # 事务超时时间

#pagehelper:  # MyBatis分页插件配置
#  helperDialect: mysql
##  reasonable: true  # 分页合理性
#  support-methods-arguments: true
#  params: count=countSql

sms:  # 短信配置
  url: http://www.api.zthysms.com/sendSms.do
  username: xiangqiandaihy
  password: 65tkXZ
  day-count: 10  # 每日短信数量
  interval-second: 60  # 短信间隔时间（单位：秒）
  expired-second: 60  # 短信过期时间（单位：秒）

task:  # 线程池配置
  pool:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    keep-alive-second: 60
    thread-name-prefix: SMS-Thread
