# ============ 公共配置 ============
spring:
  jackson:  # Jackson序列化配置
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:  # Freemarker配置
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl  # 后缀.ftl可省略
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
      auto_import: common/common.ftl as common  # 将common.ftl设置为包文件并设置别名为common

mybatis:  # MyBatis配置
  type-aliases-package: com.gedoumi.quwabao
  mapper-locations: classpath:mappers/**/**.xml  # xml文件位置
  configuration:  # 原生Mybatis配置
    cache-enabled: false  # 关闭缓存
    map-underscore-to-camel-case: true  # 是否开启自动驼峰命名规则
    use-generated-keys: true  # 自动生成主键
    default-executor-type: reuse  # 配置默认的执行器（REUSE 执行器会重用预处理语句）
    default-statement-timeout: 600  # 事务超时时间

pagehelper:  # MyBatis分页插件配置
  helperDialect: mysql
  support-methods-arguments: true
  params: count=countSql
  #  reasonable: true  # 分页合理性

task:  # 线程池配置
  pool:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    keep-alive-second: 60
    thread-name-prefix: SMS-Thread

sms:  # 短信配置
  url: http://www.trans.zthysms.com/sendSms.do
  username: xiangqiandaihy
  password: 65tkXZ
  day-count: 10  # 每日短信数量
  interval-second: 60  # 短信间隔时间（单位：秒）
  expired-second: 60  # 短信过期时间（单位：秒）

gateway: # 交易所配置
  private-key: test  # 交易所私钥
  url: http://139.198.12.20:4000
  get-eth-address: /api/v1/pfc_eth/query
  bind-eth-address: /api/v1/pfc_eth/bind
  withdraw: /api/v1/pfc/withdraw

#logging:
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(%5p) - %clr(%-40.40logger{39}){cyan} : %m%n"
